version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      electron:
        patterns:
          - "electron-*"
          - "electron"
      stylelint: 
        patterns:
          - "stylelint-*"
          - "stylelint"          
